a = input("siapa namamu?")
print("halo, selamat datang " + a)
a = input("dimana rumahmu?")
print("wah," + a)
a = input("apa buah kesukaanmu?")
print("bagus juga seleramu, " + a + " selain memiliki banyak manfaat juga berfungsi meningkatkan imun tubuh loh")
a = input("mau ngapain nih kita?")
print("kalau gitu kita main pantun aja gimana?")
a = input("nah, aku mulai ya. pucuk ubi pucuk kangkung...")
print("anjay kelaz kink")
a = input("apa ya..")
print("sama, gw juga gatau ._. ")
a = input("")
print("mau gimana sih bre, namanya juga chatbot manual xixixi")
a = input("")
print("apa aja dah, hmm gini aja... lu udh makan td?")
a = input("")
print("makan apa emg td?")
a = input("")
print("buset, kayanya enak tuh")
a = input("")
print("yaudah sampe sini dulu ya, kapan-kapan kita lanjut lagi. ")
a = input("my reaction me gua kaya this gini: ")